/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cwww_natives_NativeDemo */

#ifndef _Included_com_cwww_natives_NativeDemo
#define _Included_com_cwww_natives_NativeDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cwww_natives_NativeDemo
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cwww_natives_NativeDemo_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
